Update and rename docker-publish.yml to ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,6 @@
-name: Docker
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
+name: Continuous Integration
 
 on:
-  schedule:
-    - cron: "25 5 * * *"
   push:
     branches: ["main"]
     # Publish semver tags as releases.
@@ -16,10 +9,11 @@ on:
     branches: ["main"]
 
 env:
-  # Use docker.io for Docker Hub if empty
-  REGISTRY: ghcr.io
-  # github.repository as <account>/<repo>
-  IMAGE_NAME: ${{ github.repository }}
+  # # Use docker.io for Docker Hub if empty
+  # REGISTRY: ghcr.io
+  # # github.repository as <account>/<repo>
+  # IMAGE_NAME: ${{ github.repository }}
+  IMAGE_NAME: fiotechlabs/restful-api
 
 jobs:
   build:
@@ -34,6 +28,27 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      # Set up JDK
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: "17"
+          distribution: "temurin"
+          cache: maven
+
+      # Build with Maven
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
+
+      # Verify the target directory and JAR file exist
+      - name: Verify target directory and JAR file
+        run: |
+          if [ ! -f target/app-release.jar ]; then
+            echo "JAR file not found! Build may have failed."
+            exit 1
+          fi
+          echo "JAR file found: target/app-release.jar"
 
       # Install the cosign tool except on PR
       # https://github.com/sigstore/cosign-installer
@@ -56,8 +71,9 @@ jobs:
         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
         with:
           registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          # username: ${{ github.actor }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_SECRET_TOKEN }}
 
       # Extract metadata (tags, labels) for Docker
       # https://github.com/docker/metadata-action
